pull_request_rules:
  - name: automatic merge
    conditions:
      - base=master
      - check-success=Semantic Pull Request
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label!=work-in-progress
      - label!=manual merge
    actions:
      merge:
        strict: smart
        method: rebase
  - name: dismiss reviews except for core devs
    conditions:
      - author!=@devs
    actions:
      dismiss_reviews: {}
  - name: dismiss reviews for core devs
    conditions:
      - author=@devs
    actions:
      dismiss_reviews:
          # Do not remove approval for core devs
          approved: False
  - name: auto add wip
    conditions:
      - title~=^(wip|WIP).*
    actions:
      label:
        add: ["work-in-progress"]
  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "@{{author}} this pull request is now in conflict 😩"
      label:
        add:
          - conflict
  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict
